require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 100
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/conversation.rb

Rails/FilePath:
  Exclude:
    - spec/rails_helper.rb

RSpec/MultipleDescribes:
  Exclude:
    - spec/requests/users_spec.rb